### PR TITLE
fix ISS emissions double counting

### LINKED ISSUE #202: ISS emissions double counts for companies with multiple share classes
more info:
- https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/9942
- https://rockmtnins-my.sharepoint.com/:w:/g/personal/alalechere_rmi_org/EeiyYx7k-N5Ko98bC89rRiMBz_zawxabq-xD-MXJ4RV-lA?e=jxztC0
- https://rockmtnins.sharepoint.com/:w:/s/PACTA/EUdRdvy38CZIgCr5TcueXz4BNP6D350-AqollEUghMbZ_g?e=jjvdT7

[AB#10457](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10457)

### PR DESCRIPTION
**Pull request by cjyetman**
- closes #202

### CODE REVIEW

**Comment by Antoine-Lalechere** [comment]
@cjyetman from the call we had this morning I just pushed a change in the PR

ff_mkt_val comes now from financial_data table and not from factset_entity_financing table. The reason financial_data has a better figure than factset_entity_financing is stored here: https://rockmtnins.sharepoint.com/sites/PACTA/PACTA_Documents/Forms/AllItems.aspx?ga=1&id=%2Fsites%2FPACTA%2FPACTA%5FDocuments%2FGeneral%20Projects%2FPACTA%20Tech%2FQA%2F2022Q4%20QA%2FFactSet%20Issue%20129546254%20updated%20%5F%20Question%20about%20Market%20Value%2Eeml&parent=%2Fsites%2FPACTA%2FPACTA%5FDocuments%2FGeneral%20Projects%2FPACTA%20Tech%2FQA%2F2022Q4%20QA (footnote 2 in the methodology documentation here:
https://rockmtnins.sharepoint.com/:w:/s/PACTA/EUdRdvy38CZIgCr5TcueXz4BNP6D350-AqollEUghMbZ_g?e=jjvdT7
)

I still have a doubt independent from the methodology but:
`timestamp-20221231T000000Z_pulled-20240207T161053Z_factset_entity_financing_data` (last table we pulled debt from Factset for 2022Q4) contains 48879 different factset_entity_id and `timestamp-20231231T000000Z_pulled-20240229T181710Z_factset_entity_financing_data` 15525 factset_entity_id (last table we pulled debt from Factset for 2023Q4). Not sure how to increase this and if we changed filters during the year here but we might need to do some left_join the other way around L523-525 in the worst case (as mkt_value depends now from `factset_entity_info` and is more complete)

File: run_pacta_data_preparation.R [hunk 1]
```diff
@@ -504,20 +504,38 @@ iss_company_emissions <-
 
 logger::log_info("Formatting and saving file: \"iss_entity_emission_intensities.rds\".")
 
+factset_financial_data <-
+  readRDS(factset_financial_data_path) %>%
+  select(factset_entity_id,issue_type, adj_price, adj_shares_outstanding) %>%
```
Comment (jdhoffa) [inline run_pacta_data_preparation.R:509]:
```suggestion
  select(factset_entity_id, issue_type, adj_price, adj_shares_outstanding) %>%
```

File: run_pacta_data_preparation.R [hunk 2]
```diff
@@ -504,20 +504,38 @@ iss_company_emissions <-
...
 iss_entity_emission_intensities <-
   readRDS(factset_entity_financing_data_path) %>%
+  left_join(factset_entity_info, by = "factset_entity_id") %>%
+  filter(countrycode::countrycode(iso_country, "iso2c", "iso4217c") == currency) %>%
   left_join(currencies, by = "currency") %>%
   mutate(
-    ff_mkt_val = ff_mkt_val * exchange_rate,
-    ff_debt = ff_debt * exchange_rate,
+    ff_mkt_val = if_else(!is.na(mkt_val), mkt_val, NA_real_),
+    ff_debt = if_else(!is.na(ff_debt), ff_debt * exchange_rate, NA_real_),
```
Comment (jdhoffa) [inline run_pacta_data_preparation.R:532]: Does `mkt_val` not need to be multiplied by `exchange_rate` as well?

File: run_pacta_data_preparation.R [hunk 3]
```diff
@@ -504,20 +504,38 @@ iss_company_emissions <-
...
     currency = "USD"
   ) %>%
-  select(-exchange_rate) %>%
-  group_by(factset_entity_id, currency) %>%
   summarise(
-    ff_mkt_val = sum(ff_mkt_val, na.rm = TRUE),
-    ff_debt = sum(ff_debt, na.rm = TRUE),
-    .groups = "drop"
+    ff_mkt_val = mean(ff_mkt_val, na.rm = TRUE),
+    ff_debt = mean(ff_debt, na.rm = TRUE),
```
Comment (jdhoffa) [inline run_pacta_data_preparation.R:537]: Why are we talking the `mean` here?

**Review by jdhoffa — CHANGES_REQUESTED** [review]
See comments

File: run_pacta_data_preparation.R (hunk 2 above)
Comment (cjyetman) [reply run_pacta_data_preparation.R:532]: better answered by @Antoine-Lalechere

File: run_pacta_data_preparation.R (hunk 3 above)
Comment (cjyetman) [reply run_pacta_data_preparation.R:537]: better answered by @Antoine-Lalechere, but I think because there are slight variations between the same entity, so this is meant to average them out

File: run_pacta_data_preparation.R (hunk 2 above)
Comment (Antoine-Lalechere) [reply run_pacta_data_preparation.R:532]: Here mkt_val comes from factset_financial_data extracted from Factset Ownership bundle and all Factset Ownership data is already in USD.

File: run_pacta_data_preparation.R (hunk 3 above)
Comment (Antoine-Lalechere) [reply run_pacta_data_preparation.R:537]: exactly - there are around 150 securities for which the entity's debt may differ by a maximum of 0.1% between two securities for 2023Q4. Those data are often selected from the same timestamps it's hard to figure out where the rounding issue come from, and. that's why given the size of the issue, it has been decided to take mean here

**Review by jdhoffa — APPROVED** [review]
Comments addressed. LGTM
